name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: Ubuntu-24.04
    steps:
      - uses: action/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-versions: 16.x
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
      - run: pnpm rn ci
