name: CI

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"

      # Setup pnpm store
      - name: Setup pnpm store
        run: |
          pnpm config set store-dir .pnpm-store
          pnpm config set verify-store-integrity false

      # First try to remove any existing incompatible lock file
      - name: Clean existing lock file
        run: rm -f pnpm-lock.yaml

      # Generate a fresh lock file
      - name: Generate lock file
        run: pnpm install

      # Run CI after setup is complete
      - name: Run CI
        run: pnpm run ci
